FROM python:latest

WORKDIR /home/matching_service/

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . /home/matching_service/

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host", "--port", "8000" ]