repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files # prevents giant files from being committed.
  - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
  - id: check-merge-conflict # checks for files that contain merge conflict strings.
  - id: check-yaml # checks yaml files for parseable syntax.
  - id: detect-private-key # detects the presence of private keys.
  - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
  - id: fix-byte-order-marker # removes utf-8 byte order marker.
  - id: mixed-line-ending # replaces or checks mixed line ending.
  - id: requirements-txt-fixer # sorts entries in requirements.txt.
  - id: trailing-whitespace # trims trailing whitespace.

# Sort imports alphabetically, and automatically separated into sections and by type.
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]

# PEP 8 compliant opinionated formatter.
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

# Cleaning unused imports.
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.3
  hooks:
  - id: pycln
    args: ["-a"]

# Used to have proper type annotations for library code.
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
  hooks:
  - id: mypy
    args: [--disallow-untyped-defs, --disallow-incomplete-defs, --ignore-missing-imports]
    exclude: (/test_|tests/|experiments/)

- repo: https://github.com/PyCQA/flake8
  # Checks Python source files for errors.
  rev: 3.9.2
  hooks:
  - id: flake8
    name: flake8
    entry: flake8
    language: python
    types: [python]
    args: [--config, .flake8]
    exclude: (docs/|experiments/)

# Enforces a coding standard, looks for code smells, and can make suggestions about how the code could be refactored.
- repo: https://github.com/pycqa/pylint
  rev: v2.15.2
  hooks:
  - id: pylint
    exclude: (/test_|tests/|docs/|experiments/)
    args: ["--rcfile=pylintrc", # Link to your config file
    ]
