version: '3'
services:

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - capstone-project

  etl:
    build:
      context: ./src/etl_service
    container_name: etl-container
    environment:
      - BASE_URL='https://xloop-dummy.herokuapp.com'
    networks:
      - capstone-project
    depends_on:
      - redis

  matching:
    build: 
      context: ./src/matching_service
    container_name: matching-service
    networks:
      - capstone-project
    ports:
      - 8000:8000
    depends_on:
      - etl

networks:
  capstone-project:
    name: capstone-project