version: '3'
services:

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - capstone-project

  etl:
    build:
      context: ./src/etl_service
    container_name: etl-container
    networks:
      - capstone-project
    ports:
      - '80:80'
    depends_on:
      - redis

networks:
  capstone-project:
    name: capstone-project