FROM python:3.9

WORKDIR /home/app/

COPY . /home/app/

COPY ./requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=${PYTHONPATH}:/home/app/

CMD [ "python3", "hello.py" ]