
FROM python:3.10

WORKDIR /home/app/

COPY . /home/app/

COPY requirements.txt .


# Update package lists
RUN apt-get update

# Install OpenJDK 11 JDK
RUN apt-get install -y --no-install-recommends openjdk-17-jdk

# RUN apt-get install -y --no-install-recommends openjdk-11-jdk
RUN apt install -y redis-server

RUN pip install --no-cache-dir -r requirements.txt

# Install cron and other dependencies
RUN apt-get update && apt-get install -y cron

# Copy the cron job configuration file to the container
COPY cronjob /etc/cron.d/cronjob

# Create the log file
RUN touch /var/log/cron.log

# Give execution rights to the cron job
RUN chmod 0644 /etc/cron.d/cronjob

# Apply the cron job
RUN crontab /etc/cron.d/cronjob

# Run cron and tail the log file
CMD cron && tail -f /var/log/cron.log


